apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudshield-ingress
  labels:
    app: cloudshield
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  tls:
  - hosts:
    - cloudshield.yourdomain.com
    - api.cloudshield.yourdomain.com
    secretName: cloudshield-tls-secret
  rules:
  - host: cloudshield.yourdomain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cloudshield-api-service
            port:
              number: 8000
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: cloudshield-api-service
            port:
              number: 8000
      - path: /redoc
        pathType: Prefix
        backend:
          service:
            name: cloudshield-api-service
            port:
              number: 8000
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: cloudshield-api-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudshield-frontend-service
            port:
              number: 80
  - host: api.cloudshield.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudshield-api-service
            port:
              number: 8000

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudshield-secrets
type: Opaque
stringData:
  database-url: "postgresql://cloudshield_user:your_secure_password@postgres-service:5432/cloudshield"
  redis-url: "redis://redis-service:6379/0"
  secret-key: "your-ultra-secure-secret-key-change-this-in-production"
  slack-webhook-url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"

---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
type: Opaque
stringData:
  google-client-id: "your-google-client-id"
  google-client-secret: "your-google-client-secret"
  microsoft-client-id: "your-microsoft-client-id"
  microsoft-client-secret: "your-microsoft-client-secret"
  slack-client-id: "your-slack-client-id"
  slack-client-secret: "your-slack-client-secret"
  github-client-id: "your-github-client-id"
  github-client-secret: "your-github-client-secret"
  notion-client-id: "your-notion-client-id"
  notion-client-secret: "your-notion-client-secret"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  username: "cloudshield_user"
  password: "your_secure_database_password"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudshield-config
data:
  environment: "production"
  log_level: "INFO"
  max_scan_workers: "4"
  scan_interval_minutes: "60"
  alert_cooldown_minutes: "30"
  oauth_token_refresh_minutes: "30"
